import './gsap.module.scss'
import TextAnimation from "./component/text-animation";

export const metadata = {
  title: 'GSAP',
  description: 'Generated by create next app',
}

export default function GSAP() {
  return (
    <main className="wrapper-all">
      <div className="title">
        <div>
          <h1>GSAP Test</h1>
          <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eum maxime, porro quis quo doloribus vitae optio. Voluptates exercitationem perferendis culpa modi consequatur beatae dicta dignissimos.</p>
        </div>
      </div>
      <TextAnimation />
      <div className="wrapper-horizontal">
        <div id="first" className="panel">
          Scroll down to animate horizontally
        </div>
        <div id="second" className="panel"></div>
        <div id="third" className="panel"></div>
        <div id="fourth" className="panel"></div>
      </div>
      <div className="title">
        <div>
          <h1>GSAP Test</h1>
          <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eum maxime, porro quis quo doloribus vitae optio. Voluptates exercitationem perferendis culpa modi consequatur beatae dicta dignissimos.</p>
        </div>
      </div>
    </main>
  )
}
